### ISSUE TITLE
Punchlist

### ISSUE THREAD

**Issue by vragosta** [vragosta/vincentragosta#13]
## TODO
- [ ] Create set of helper CSS for posts.
- [ ] Adjust margin for all elements inside #single-post .content ( h4, p, pre etc. ).
- [ ] Alter featured page widget to display a post also.
- [ ] Make the news and updates widget display 4 posts ( for blog posts ) instead of 3.
- [ ] Consider changing the name of news-and-updates widget.
- [ ] Rework button logic for featured page widget.
- [ ] Set image fallback in the event no image is set.
- [ ] Create different pagination for single blog.
- [ ] New look and feel for archive pagination.
- [ ] Fix spacing with footer elements.
- [ ] Give author and date a link on the blog.
- [ ] Set up comment system for the single blog.
- [ ] Ensure the commenting in the header/sub header files are orthogonal.
- [ ] Consider changing how the fonts are being used in the css.
- [ ] Create algorithm to figure out which aside-front-page-X.php to use based off sidebar that the widget is coming from.
- [ ] Create sidebar for blog page.
- [ ] Make the widgets plugins to modularize the css and keep the code isolated.
- [ ] Make admin.js an object when porting over js to plugin.
- [ ] Resolve js issues in admin.js ( frankies code ).
- [ ] Set up taxonomy 'Wordpress' for projects cpt, or consider removing entirely and put something else.
- [ ] Install grunt.
- [ ] Create 404.php.
- [ ] wp_script_is not working.
- [ ] Build maintenance plugin.
- [ ] Browser check the site.
- [ ] Consider adding more meta to comments in assets/css.
- [ ] See if its possible to only display CSS of widgets if they are in use ( image captions ).
- [ ] Make the important documents a dynamic menu.
- [ ] Add GH Tag for v1.0 upon release.

## NEED TO BE SORTED
- [ ] Consider fixing the spacing above VIEW PROJECTS to match the spacing beneath.
- [ ] Consider placement of X in mobile menu, maybe have 'Close' button at bottom? ( rework mobile menu altogether ).
- [ ] Create Instagram plugin.
- [ ] Create README.md for image plugin and theme.
- [ ] Get js behavior on pre-footer.
- [ ] Consider adding max-width: 800px for portfolio page (???).
- [ ] If you shrink the font-size of the menu items ( header by removing code shop ), you can potentially collapse the menu at 768px.
- [ ] Hover effect for images on blog archive.
- [ ] Add `rel="noopener noreferrer"` to all target="_blank".

## COMPLETED
- [x] Merge Featured Post Widget into News & Updates Widget.
- [x] Change CTA styles to Sidebar styles.
- [x] Pre Footer.
- [x] Footer.
- [x] Media Queries for Front page.
- [x] Set up hover functionality for social partial.
- [x] Comb through CSS and refine like elements.
- [x] Give user control over color scheme of Sidebars and Widgets?.
- [x] Single Template.
- [x] TOP PRIORITY: Change featured post widget into featured page.
- [x] Format date in news and updates widget.
- [x] Make Social Links user meta.
- [x] Make Images in archive-project an image plugin ( [image src="" class="small/medium/large"] ).
- [x] Change dropdown button to ionicon hamburger button.
- [x] Change ".sidebar" to ".aside".
- [x] Add styled < h r / > elements on single template.
- [x] Modularize footer with get_template_part().
- [x] Modularize CSS for the various features of the site ( widgets, single, archive, front-page, etc. ). Then organize what remains in the css file.
- [x] Find a way to combine the code for the header image background with the featured-page image background...they can easily be the same thing.
- [x] Create a partial for featured image overlay ( Maybe ties into bullet point # 12 ).
- [x] Figure out a way to combine header/heading, and title, create one modularized set.
- [x] ~~Make `include( locate_template( ) )` a function in the helpers file.~~
- [x] Modularize both featured image overlay for header/featured-post and featured image overlay for news-and-updates/archive.
- [x] Add featured-overlay to featured page, and header, also figure out fix for permalink button in template.#header ( maybe add to #menu ).
- [x] Single template plugin fixes.
- [x] Single breakpoint for header container.
- [x] Change `#news-and-updates .post-type` CSS to is_archive() in helpers function.
- [x] Clean up conditional in helpers.css for image caption ( can def make it more efficient ).
- [x] ~~Make this a function:  `<?php include( VINCENTRAGOSTA_IMAGE_CAPTION_PATH . 'partials/aside-sub-header.php' ); ?>`.~~
- [x] Use `get_post_meta()` for getting the button text as opposed to having to put on shortcode.
- [x] Extract image caption relevant metaboxes from theme, and find a way to hook them into functions.php from the plugin.
- [x] Change name of image captions to just image-captions ( remove vincentragosta ).
- [x] Consider the placement of the get_post_meta functions in the partial files.
- [x] Do something with #contact button CSS, either rename it or make it a stand-alone.
- [x] Consider making `$sub_header_class  = ( is_single() ) ? 'big' : 'small';` a function or at least a variable.
- [x] Create helpers.css in theme and check against that file to display the helpers.css of the plugin image caption.
- [x] Change 'section-XXXX' to 'content-XXXX'.
- [x] Rename the 'post-type' class from the overlay partial.
- [x] CSS transition behavior to image caption plugin.
- [x] Menu fade in on page load.
- [x] ~~Consider making a max-width for sub-header.~~
- [x] ~~See if it is possible to create sub-folders in the partials folder.~~
- [x] Finish all comments in image-caption plugin.
- [x] Namespace the various includes/functions files.
- [x] Consider adding featured page widget to image-captions plugin.
- [x] Revisit big, small and static classes, maybe we can combine big/static ( If that is possible, rename the jargon ).
- [x] Add phone number to user meta and call from contact-info partial.
- [x] Make $user_id a define.
- [x] Re work the pagination so that the core styles are the same but slightly different on single and archive templates.
- [x] ~~Make `date_format( date_create( $post->post_date ), 'jS F Y' )` a function in the helpers file.~~
- [x] Shift 'X' in mobile menu to match positioning of hamburger button.
- [x] Fix the bug in the hamburger button when clicked, closed, and screen size adjusted from small to medium/large.
- [x] Fix fade out of mobile menu.
- [x] Remove visible/not-visible from helpers CSS, should only be on specific elements ( listed as TODO in code ).
- [x] ~~Can 'i' element be added to core-components with color: #fff?~~
- [x] Fix .aside.excerpt, maybe add #portfolio back.
- [x] IMPORTANT: Make sure the image-captions plugin is not using any of the theme CSS.
- [x] Finish commenting theme CSS, theme JS.
- [x] Research wp_enqueue_script/style(), the 'all' at the bottom.
- [x] Put conditionals around the social menu items.
- [x] Fix all occurences of if ( condition ) { action } => if ( condition ) action.
- [x] Remove all occurences of !important ( should be one somewhere in the code ).
- [x] Important: Resolve z-index issue with menu ( toggle menu instead of menu-container ).
- [x] Ensure the MQ dimensions are correct across site.
- [x] Remove esc_html from metabox html function.
- [x] Namespace core.php in image-plugins.
- [x] Refine files so that @package only appears at the top of the comments section in the file and is properly referencing the package.
- [x] ~~Consider removing set_post_thumbnail_size().~~
- [x] Ensure all php comments are aligned properly.
- [x] Ensure sanitize_text_field is used correctly in conjunction with trim() and strip_tags() in the various metabox files.
- [x] Research GH Tags ( versioning on GH ).
- [x] ~~Make the menu dynamic by using wp-admin.~~
- [x] ~~Make social icon menu dynamic by using wp-admin.~~
- [x] Adjust metabox width in wp-admin.
- [x] Get logo up on site. 
- [x] Unloaded effect on logo.
- [x] Confirm use of all defines.
- [x] Research schemas, itemscope and itemprop attributes.
- [x] Implement use of schemas.
- [x] Make mobile menu have a transparent background.
- [x] ~~Resolve regression if the mobile menu is open when the screen size is increased.~~
- [x] ~~Consider padding on single template at lower media queries. (???)~~
- [x] Create format_date function for image captions.
- [x] Change posts per page for posts, use sc method but refresh permalinks once completed.
- [x] Create blog archive template.
- [x] Style blog pagination.
- [x] Resolve regression in js functionality for image-captions.
- [x] Change format for date to read December 11th, 2016.
- [x] Add Read Post-> to the bottom of each post on blog.
- [x] Create category tags for projects and posts, consider replacing wordpress site with the category tag, also add category tag above the post in the blog archive.
- [x] format_date function for image_captions plugin.
- [x] ~~Create hover effect on Read Post->.~~

**Comment by vragosta** [comment]
Consider making a max-width for sub-header.
![screen shot 2017-01-22 at 1 33 07 pm](https://cloud.githubusercontent.com/assets/10521070/22184783/5fe4bf22-e0a7-11e6-90df-ff44880b194c.png)
